=== CorentinDespierre/EDUPAIX/BasesXML/Départs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Départs" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Départs">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="N_x00B0_dépt " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAA/SytRRG/iSY3HOfMITKlIAAAAAOkiIitRLORA/PFcL8QIYwBEAOkA
cABhAHIAdABzAAAAAAAAAJeBkuLH0gNDtun4npXOKFkAAAAAoCaD2lAs5EAAAAAA
HHgqAEMAbwBtAGkAdADpAHMAAAAAAAAAju9wvQc8FUu6ngjrL+ZHhAcAAAA/SytR
RG/iSY3HOfMITKlITgCwAGQA6QBwAHQAAAAAAAAAuGsDMhGv1km+/ky6Ml7+9wcA
AAA/SytRRG/iSY3HOfMITKlIRADpAHAAYQByAHQAZQBtAGUAbgB0AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="GUID" type="9" value="P0srUURv4kmNxznzCEypSA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="N_x00B0_dépt" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1200"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="ju9wvQc8FUu6ngjrL+ZHhA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Département" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="uGsDMhGv1km+/ky6Ml7+9w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== CorentinDespierre/EDUPAIX/BasesXML/Départs.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Départs.xsd" generated="2018-03-23T09:21:52">
<Départs>
<N_x00B0_dépt>1</N_x00B0_dépt>
<Département>Ain</Département>
</Départs>
<Départs>
<N_x00B0_dépt>2</N_x00B0_dépt>
<Département>Aisne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>3</N_x00B0_dépt>
<Département>Allier</Département>
</Départs>
<Départs>
<N_x00B0_dépt>4</N_x00B0_dépt>
<Département>Alpes de Haute-Provence</Département>
</Départs>
<Départs>
<N_x00B0_dépt>5</N_x00B0_dépt>
<Département>Hautes-Alpes</Département>
</Départs>
<Départs>
<N_x00B0_dépt>6</N_x00B0_dépt>
<Département>Alpes-Maritimes</Département>
</Départs>
<Départs>
<N_x00B0_dépt>7</N_x00B0_dépt>
<Département>Ardêche</Département>
</Départs>
<Départs>
<N_x00B0_dépt>8</N_x00B0_dépt>
<Département>Ardennes</Département>
</Départs>
<Départs>
<N_x00B0_dépt>9</N_x00B0_dépt>
<Département>Ariège</Département>
</Départs>
<Départs>
<N_x00B0_dépt>10</N_x00B0_dépt>
<Département>Aube</Département>
</Départs>
<Départs>
<N_x00B0_dépt>11</N_x00B0_dépt>
<Département>Aude</Département>
</Départs>
<Départs>
<N_x00B0_dépt>12</N_x00B0_dépt>
<Département>Aveyron</Département>
</Départs>
<Départs>
<N_x00B0_dépt>13</N_x00B0_dépt>
<Département>Bouches-du-Rhöne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>14</N_x00B0_dépt>
<Département>Calvados</Département>
</Départs>
<Départs>
<N_x00B0_dépt>15</N_x00B0_dépt>
<Département>Cantal</Département>
</Départs>
<Départs>
<N_x00B0_dépt>16</N_x00B0_dépt>
<Département>Charente</Département>
</Départs>
<Départs>
<N_x00B0_dépt>17</N_x00B0_dépt>
<Département>Charente-Maritime</Département>
</Départs>
<Départs>
<N_x00B0_dépt>18</N_x00B0_dépt>
<Département>Cher</Département>
</Départs>
<Départs>
<N_x00B0_dépt>19</N_x00B0_dépt>
<Département>Corrèze</Département>
</Départs>
<Départs>
<N_x00B0_dépt>20</N_x00B0_dépt>
<Département>Corse</Département>
</Départs>
<Départs>
<N_x00B0_dépt>21</N_x00B0_dépt>
<Département>cöte-d&apos;Or</Département>
</Départs>
<Départs>
<N_x00B0_dépt>22</N_x00B0_dépt>
<Département>Côtes d&apos;Armor</Département>
</Départs>
<Départs>
<N_x00B0_dépt>23</N_x00B0_dépt>
<Département>Creuse</Département>
</Départs>
<Départs>
<N_x00B0_dépt>24</N_x00B0_dépt>
<Département>Dordogne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>25</N_x00B0_dépt>
<Département>Doubs</Département>
</Départs>
<Départs>
<N_x00B0_dépt>26</N_x00B0_dépt>
<Département>Drôme</Département>
</Départs>
<Départs>
<N_x00B0_dépt>27</N_x00B0_dépt>
<Département>Eure</Département>
</Départs>
<Départs>
<N_x00B0_dépt>28</N_x00B0_dépt>
<Département>Eure-et-Loir</Département>
</Départs>
<Départs>
<N_x00B0_dépt>29</N_x00B0_dépt>
<Département>Finistère</Département>
</Départs>
<Départs>
<N_x00B0_dépt>30</N_x00B0_dépt>
<Département>Gard</Département>
</Départs>
<Départs>
<N_x00B0_dépt>31</N_x00B0_dépt>
<Département>Haute-Garonne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>32</N_x00B0_dépt>
<Département>Gers</Département>
</Départs>
<Départs>
<N_x00B0_dépt>33</N_x00B0_dépt>
<Département>Gironde</Département>
</Départs>
<Départs>
<N_x00B0_dépt>34</N_x00B0_dépt>
<Département>Hérault</Département>
</Départs>
<Départs>
<N_x00B0_dépt>35</N_x00B0_dépt>
<Département>Île-et-Vilaine</Département>
</Départs>
<Départs>
<N_x00B0_dépt>36</N_x00B0_dépt>
<Département>Indre</Département>
</Départs>
<Départs>
<N_x00B0_dépt>37</N_x00B0_dépt>
<Département>Indre-et-Loire</Département>
</Départs>
<Départs>
<N_x00B0_dépt>38</N_x00B0_dépt>
<Département>Isère</Département>
</Départs>
<Départs>
<N_x00B0_dépt>39</N_x00B0_dépt>
<Département>Jura</Département>
</Départs>
<Départs>
<N_x00B0_dépt>40</N_x00B0_dépt>
<Département>Landes</Département>
</Départs>
<Départs>
<N_x00B0_dépt>41</N_x00B0_dépt>
<Département>Loir-et-Cher</Département>
</Départs>
<Départs>
<N_x00B0_dépt>42</N_x00B0_dépt>
<Département>Loire</Département>
</Départs>
<Départs>
<N_x00B0_dépt>43</N_x00B0_dépt>
<Département>Haute-Loire</Département>
</Départs>
<Départs>
<N_x00B0_dépt>44</N_x00B0_dépt>
<Département>Loire-Atlantique</Département>
</Départs>
<Départs>
<N_x00B0_dépt>45</N_x00B0_dépt>
<Département>Loiret</Département>
</Départs>
<Départs>
<N_x00B0_dépt>46</N_x00B0_dépt>
<Département>Lot</Département>
</Départs>
<Départs>
<N_x00B0_dépt>47</N_x00B0_dépt>
<Département>Lot-et-Garonne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>48</N_x00B0_dépt>
<Département>Lozère</Département>
</Départs>
<Départs>
<N_x00B0_dépt>49</N_x00B0_dépt>
<Département>Maine-et-Loire</Département>
</Départs>
<Départs>
<N_x00B0_dépt>50</N_x00B0_dépt>
<Département>Manche</Département>
</Départs>
<Départs>
<N_x00B0_dépt>51</N_x00B0_dépt>
<Département>Marne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>52</N_x00B0_dépt>
<Département>Haute-Marne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>53</N_x00B0_dépt>
<Département>Mayenne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>54</N_x00B0_dépt>
<Département>Meuthe-et-Moselle</Département>
</Départs>
<Départs>
<N_x00B0_dépt>55</N_x00B0_dépt>
<Département>Meuse</Département>
</Départs>
<Départs>
<N_x00B0_dépt>56</N_x00B0_dépt>
<Département>Morbihan</Département>
</Départs>
<Départs>
<N_x00B0_dépt>57</N_x00B0_dépt>
<Département>Moselle</Département>
</Départs>
<Départs>
<N_x00B0_dépt>58</N_x00B0_dépt>
<Département>Nièvre</Département>
</Départs>
<Départs>
<N_x00B0_dépt>59</N_x00B0_dépt>
<Département>Nord</Département>
</Départs>
<Départs>
<N_x00B0_dépt>60</N_x00B0_dépt>
<Département>Oise</Département>
</Départs>
<Départs>
<N_x00B0_dépt>61</N_x00B0_dépt>
<Département>Orne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>62</N_x00B0_dépt>
<Département>Pas-de-Calais</Département>
</Départs>
<Départs>
<N_x00B0_dépt>63</N_x00B0_dépt>
<Département>Puy-de-Dôme</Département>
</Départs>
<Départs>
<N_x00B0_dépt>64</N_x00B0_dépt>
<Département>Pyrénées-Atlantiques</Département>
</Départs>
<Départs>
<N_x00B0_dépt>65</N_x00B0_dépt>
<Département>Hautes-Pyrénées</Département>
</Départs>
<Départs>
<N_x00B0_dépt>66</N_x00B0_dépt>
<Département>Pyrénées-Orientales</Département>
</Départs>
<Départs>
<N_x00B0_dépt>67</N_x00B0_dépt>
<Département>Bas-Rhin</Département>
</Départs>
<Départs>
<N_x00B0_dépt>68</N_x00B0_dépt>
<Département>Haut-Rhin</Département>
</Départs>
<Départs>
<N_x00B0_dépt>69</N_x00B0_dépt>
<Département>Rhône</Département>
</Départs>
<Départs>
<N_x00B0_dépt>70</N_x00B0_dépt>
<Département>Haute-Saône</Département>
</Départs>
<Départs>
<N_x00B0_dépt>71</N_x00B0_dépt>
<Département>Saône-et-Loire</Département>
</Départs>
<Départs>
<N_x00B0_dépt>72</N_x00B0_dépt>
<Département>Sarthe</Département>
</Départs>
<Départs>
<N_x00B0_dépt>73</N_x00B0_dépt>
<Département>Savoie</Département>
</Départs>
<Départs>
<N_x00B0_dépt>74</N_x00B0_dépt>
<Département>Haute-Savoie</Département>
</Départs>
<Départs>
<N_x00B0_dépt>75</N_x00B0_dépt>
<Département>Paris</Département>
</Départs>
<Départs>
<N_x00B0_dépt>76</N_x00B0_dépt>
<Département>Seine-Maritime</Département>
</Départs>
<Départs>
<N_x00B0_dépt>77</N_x00B0_dépt>
<Département>Seine-et-Marne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>78</N_x00B0_dépt>
<Département>Yvelines</Département>
</Départs>
<Départs>
<N_x00B0_dépt>79</N_x00B0_dépt>
<Département>Deux-Sèvres</Département>
</Départs>
<Départs>
<N_x00B0_dépt>80</N_x00B0_dépt>
<Département>Somme</Département>
</Départs>
<Départs>
<N_x00B0_dépt>81</N_x00B0_dépt>
<Département>Tarn</Département>
</Départs>
<Départs>
<N_x00B0_dépt>82</N_x00B0_dépt>
<Département>Tarn-et-Garonne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>83</N_x00B0_dépt>
<Département>Var</Département>
</Départs>
<Départs>
<N_x00B0_dépt>84</N_x00B0_dépt>
<Département>Vaucluse</Département>
</Départs>
<Départs>
<N_x00B0_dépt>85</N_x00B0_dépt>
<Département>Vendée</Département>
</Départs>
<Départs>
<N_x00B0_dépt>86</N_x00B0_dépt>
<Département>Vienne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>87</N_x00B0_dépt>
<Département>Haute-Vienne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>88</N_x00B0_dépt>
<Département>Vosges</Département>
</Départs>
<Départs>
<N_x00B0_dépt>89</N_x00B0_dépt>
<Département>Yonne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>90</N_x00B0_dépt>
<Département>Territoire-de-Belfort</Département>
</Départs>
<Départs>
<N_x00B0_dépt>91</N_x00B0_dépt>
<Département>Essonne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>92</N_x00B0_dépt>
<Département>Hauts-de-Seine</Département>
</Départs>
<Départs>
<N_x00B0_dépt>93</N_x00B0_dépt>
<Département>Seine-Saint-Denis</Département>
</Départs>
<Départs>
<N_x00B0_dépt>94</N_x00B0_dépt>
<Département>Val-de-Marne</Département>
</Départs>
<Départs>
<N_x00B0_dépt>95</N_x00B0_dépt>
<Département>Val-d&apos;Oise</Département>
</Départs>
<Départs>
<N_x00B0_dépt>96</N_x00B0_dépt>
</Départs>
<Départs>
<N_x00B0_dépt>97</N_x00B0_dépt>
<Département>Dom-Tom</Département>
</Départs>
<Départs>
<N_x00B0_dépt>98</N_x00B0_dépt>
<Département>Dom-Tom</Département>
</Départs>
<Départs>
<N_x00B0_dépt>99</N_x00B0_dépt>
<Département>Etranger</Département>
</Départs>
<Départs>
<N_x00B0_dépt>101</N_x00B0_dépt>
<Département>Saisie en vrac</Département>
</Départs>
</dataroot>
