=== CorentinDespierre/EDUPAIX/BasesXML/Départements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Départements" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Départements">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="DépartementsDépartement" index-key="Département " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="N_x00B0_dép " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="4EBK62vn3Em9iESVla3LvQ==
"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADgQErra+fcSb2IRJWVrcu9AAAAAEXVdDPNDeVANVmEGv7///9EAOkA
cABhAHIAdABlAG0AZQBuAHQAcwAAAAAAAADZ1pUgYB6fTKE10VF1DTwQBwAAAOBA
Sutr59xJvYhElZWty71OALAAZADpAHAAAAAAAAAAcmPPVSMzIEKxhikTFSaSNQcA
AADgQErra+fcSb2IRJWVrcu9RADpAHAAYQByAHQAZQBtAGUAbgB0AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[Départements].[N°dép]"/>
<od:tableProperty name="SubdatasheetName" type="10" value="[Auto]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="N_x00B0_dép" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1005"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="2daVIGAen0yhNdFRdQ08EA==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Département" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="cmPPVSMzIEKxhikTFSaSNQ==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== CorentinDespierre/EDUPAIX/BasesXML/Départements.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Départements.xsd" generated="2018-03-23T09:21:46">
<Départements>
<N_x00B0_dép>1</N_x00B0_dép>
<Département>Ain</Département>
</Départements>
<Départements>
<N_x00B0_dép>2</N_x00B0_dép>
<Département>Aisne</Département>
</Départements>
<Départements>
<N_x00B0_dép>3</N_x00B0_dép>
<Département>Allier</Département>
</Départements>
<Départements>
<N_x00B0_dép>4</N_x00B0_dép>
<Département>Alpes de Haute-Provence</Département>
</Départements>
<Départements>
<N_x00B0_dép>5</N_x00B0_dép>
<Département>Hautes-Alpes</Département>
</Départements>
<Départements>
<N_x00B0_dép>6</N_x00B0_dép>
<Département>Alpes-Maritimes</Département>
</Départements>
<Départements>
<N_x00B0_dép>7</N_x00B0_dép>
<Département>Ardêche</Département>
</Départements>
<Départements>
<N_x00B0_dép>8</N_x00B0_dép>
<Département>Ardennes</Département>
</Départements>
<Départements>
<N_x00B0_dép>9</N_x00B0_dép>
<Département>Ariège</Département>
</Départements>
<Départements>
<N_x00B0_dép>10</N_x00B0_dép>
<Département>Aube</Département>
</Départements>
<Départements>
<N_x00B0_dép>11</N_x00B0_dép>
<Département>Aude</Département>
</Départements>
<Départements>
<N_x00B0_dép>12</N_x00B0_dép>
<Département>Aveyron</Département>
</Départements>
<Départements>
<N_x00B0_dép>13</N_x00B0_dép>
<Département>Bouches-du-Rhöne</Département>
</Départements>
<Départements>
<N_x00B0_dép>14</N_x00B0_dép>
<Département>Calvados</Département>
</Départements>
<Départements>
<N_x00B0_dép>15</N_x00B0_dép>
<Département>Cantal</Département>
</Départements>
<Départements>
<N_x00B0_dép>16</N_x00B0_dép>
<Département>Charente</Département>
</Départements>
<Départements>
<N_x00B0_dép>17</N_x00B0_dép>
<Département>Charente-Maritime</Département>
</Départements>
<Départements>
<N_x00B0_dép>18</N_x00B0_dép>
<Département>Cher</Département>
</Départements>
<Départements>
<N_x00B0_dép>19</N_x00B0_dép>
<Département>Corrèze</Département>
</Départements>
<Départements>
<N_x00B0_dép>20</N_x00B0_dép>
<Département>Corse</Département>
</Départements>
<Départements>
<N_x00B0_dép>21</N_x00B0_dép>
<Département>cöte-d&apos;Or</Département>
</Départements>
<Départements>
<N_x00B0_dép>22</N_x00B0_dép>
<Département>Côtes d&apos;Armor</Département>
</Départements>
<Départements>
<N_x00B0_dép>23</N_x00B0_dép>
<Département>Creuse</Département>
</Départements>
<Départements>
<N_x00B0_dép>24</N_x00B0_dép>
<Département>Dordogne</Département>
</Départements>
<Départements>
<N_x00B0_dép>25</N_x00B0_dép>
<Département>Doubs</Département>
</Départements>
<Départements>
<N_x00B0_dép>26</N_x00B0_dép>
<Département>Drôme</Département>
</Départements>
<Départements>
<N_x00B0_dép>27</N_x00B0_dép>
<Département>Eure</Département>
</Départements>
<Départements>
<N_x00B0_dép>28</N_x00B0_dép>
<Département>Eure-et-Loir</Département>
</Départements>
<Départements>
<N_x00B0_dép>29</N_x00B0_dép>
<Département>Finistère</Département>
</Départements>
<Départements>
<N_x00B0_dép>30</N_x00B0_dép>
<Département>Gard</Département>
</Départements>
<Départements>
<N_x00B0_dép>31</N_x00B0_dép>
<Département>Haute-Garonne</Département>
</Départements>
<Départements>
<N_x00B0_dép>32</N_x00B0_dép>
<Département>Gers</Département>
</Départements>
<Départements>
<N_x00B0_dép>33</N_x00B0_dép>
<Département>Gironde</Département>
</Départements>
<Départements>
<N_x00B0_dép>34</N_x00B0_dép>
<Département>Hérault</Département>
</Départements>
<Départements>
<N_x00B0_dép>35</N_x00B0_dép>
<Département>Île-et-Vilaine</Département>
</Départements>
<Départements>
<N_x00B0_dép>36</N_x00B0_dép>
<Département>Indre</Département>
</Départements>
<Départements>
<N_x00B0_dép>37</N_x00B0_dép>
<Département>Indre-et-Loire</Département>
</Départements>
<Départements>
<N_x00B0_dép>38</N_x00B0_dép>
<Département>Isère</Département>
</Départements>
<Départements>
<N_x00B0_dép>39</N_x00B0_dép>
<Département>Jura</Département>
</Départements>
<Départements>
<N_x00B0_dép>40</N_x00B0_dép>
<Département>Landes</Département>
</Départements>
<Départements>
<N_x00B0_dép>41</N_x00B0_dép>
<Département>Loir-et-Cher</Département>
</Départements>
<Départements>
<N_x00B0_dép>42</N_x00B0_dép>
<Département>Loire</Département>
</Départements>
<Départements>
<N_x00B0_dép>43</N_x00B0_dép>
<Département>Haute-Loire</Département>
</Départements>
<Départements>
<N_x00B0_dép>44</N_x00B0_dép>
<Département>Loire-Atlantique</Département>
</Départements>
<Départements>
<N_x00B0_dép>45</N_x00B0_dép>
<Département>Loiret</Département>
</Départements>
<Départements>
<N_x00B0_dép>46</N_x00B0_dép>
<Département>Lot</Département>
</Départements>
<Départements>
<N_x00B0_dép>47</N_x00B0_dép>
<Département>Lot-et-Garonne</Département>
</Départements>
<Départements>
<N_x00B0_dép>48</N_x00B0_dép>
<Département>Lozère</Département>
</Départements>
<Départements>
<N_x00B0_dép>49</N_x00B0_dép>
<Département>Maine-et-Loire</Département>
</Départements>
<Départements>
<N_x00B0_dép>50</N_x00B0_dép>
<Département>Manche</Département>
</Départements>
<Départements>
<N_x00B0_dép>51</N_x00B0_dép>
<Département>Marne</Département>
</Départements>
<Départements>
<N_x00B0_dép>52</N_x00B0_dép>
<Département>Haute-Marne</Département>
</Départements>
<Départements>
<N_x00B0_dép>53</N_x00B0_dép>
<Département>Mayenne</Département>
</Départements>
<Départements>
<N_x00B0_dép>54</N_x00B0_dép>
<Département>Meuthe-et-Moselle</Département>
</Départements>
<Départements>
<N_x00B0_dép>55</N_x00B0_dép>
<Département>Meuse</Département>
</Départements>
<Départements>
<N_x00B0_dép>56</N_x00B0_dép>
<Département>Morbihan</Département>
</Départements>
<Départements>
<N_x00B0_dép>57</N_x00B0_dép>
<Département>Moselle</Département>
</Départements>
<Départements>
<N_x00B0_dép>58</N_x00B0_dép>
<Département>Nièvre</Département>
</Départements>
<Départements>
<N_x00B0_dép>59</N_x00B0_dép>
<Département>Nord</Département>
</Départements>
<Départements>
<N_x00B0_dép>60</N_x00B0_dép>
<Département>Oise</Département>
</Départements>
<Départements>
<N_x00B0_dép>61</N_x00B0_dép>
<Département>Orne</Département>
</Départements>
<Départements>
<N_x00B0_dép>62</N_x00B0_dép>
<Département>Pas-de-Calais</Département>
</Départements>
<Départements>
<N_x00B0_dép>63</N_x00B0_dép>
<Département>Puy-de-Dôme</Département>
</Départements>
<Départements>
<N_x00B0_dép>64</N_x00B0_dép>
<Département>Pyrénées-Atlantiques</Département>
</Départements>
<Départements>
<N_x00B0_dép>65</N_x00B0_dép>
<Département>Hautes-Pyrénées</Département>
</Départements>
<Départements>
<N_x00B0_dép>66</N_x00B0_dép>
<Département>Pyrénées-Orientales</Département>
</Départements>
<Départements>
<N_x00B0_dép>67</N_x00B0_dép>
<Département>Bas-Rhin</Département>
</Départements>
<Départements>
<N_x00B0_dép>68</N_x00B0_dép>
<Département>Haut-Rhin</Département>
</Départements>
<Départements>
<N_x00B0_dép>69</N_x00B0_dép>
<Département>Rhône</Département>
</Départements>
<Départements>
<N_x00B0_dép>70</N_x00B0_dép>
<Département>Haute-Saône</Département>
</Départements>
<Départements>
<N_x00B0_dép>71</N_x00B0_dép>
<Département>Saône-et-Loire</Département>
</Départements>
<Départements>
<N_x00B0_dép>72</N_x00B0_dép>
<Département>Sarthe</Département>
</Départements>
<Départements>
<N_x00B0_dép>73</N_x00B0_dép>
<Département>Savoie</Département>
</Départements>
<Départements>
<N_x00B0_dép>74</N_x00B0_dép>
<Département>Haute-Savoie</Département>
</Départements>
<Départements>
<N_x00B0_dép>75</N_x00B0_dép>
<Département>Paris</Département>
</Départements>
<Départements>
<N_x00B0_dép>76</N_x00B0_dép>
<Département>Seine-Maritime</Département>
</Départements>
<Départements>
<N_x00B0_dép>77</N_x00B0_dép>
<Département>Seine-et-Marne</Département>
</Départements>
<Départements>
<N_x00B0_dép>78</N_x00B0_dép>
<Département>Yvelines</Département>
</Départements>
<Départements>
<N_x00B0_dép>79</N_x00B0_dép>
<Département>Deux-Sèvres</Département>
</Départements>
<Départements>
<N_x00B0_dép>80</N_x00B0_dép>
<Département>Somme</Département>
</Départements>
<Départements>
<N_x00B0_dép>81</N_x00B0_dép>
<Département>Tarn</Département>
</Départements>
<Départements>
<N_x00B0_dép>82</N_x00B0_dép>
<Département>Tarn-et-Garonne</Département>
</Départements>
<Départements>
<N_x00B0_dép>83</N_x00B0_dép>
<Département>Var</Département>
</Départements>
<Départements>
<N_x00B0_dép>84</N_x00B0_dép>
<Département>Vaucluse</Département>
</Départements>
<Départements>
<N_x00B0_dép>85</N_x00B0_dép>
<Département>Vendée</Département>
</Départements>
<Départements>
<N_x00B0_dép>86</N_x00B0_dép>
<Département>Vienne</Département>
</Départements>
<Départements>
<N_x00B0_dép>87</N_x00B0_dép>
<Département>Haute-Vienne</Département>
</Départements>
<Départements>
<N_x00B0_dép>88</N_x00B0_dép>
<Département>Vosges</Département>
</Départements>
<Départements>
<N_x00B0_dép>89</N_x00B0_dép>
<Département>Yonne</Département>
</Départements>
<Départements>
<N_x00B0_dép>90</N_x00B0_dép>
<Département>Territoire-de-Belfort</Département>
</Départements>
<Départements>
<N_x00B0_dép>91</N_x00B0_dép>
<Département>Essonne</Département>
</Départements>
<Départements>
<N_x00B0_dép>92</N_x00B0_dép>
<Département>Hauts-de-Seine</Département>
</Départements>
<Départements>
<N_x00B0_dép>93</N_x00B0_dép>
<Département>Seine-Saint-Denis</Département>
</Départements>
<Départements>
<N_x00B0_dép>94</N_x00B0_dép>
<Département>Val-de-Marne</Département>
</Départements>
<Départements>
<N_x00B0_dép>95</N_x00B0_dép>
<Département>Val-d&apos;Oise</Département>
</Départements>
<Départements>
<N_x00B0_dép>96</N_x00B0_dép>
</Départements>
<Départements>
<N_x00B0_dép>97</N_x00B0_dép>
<Département>Dom-Tom</Département>
</Départements>
<Départements>
<N_x00B0_dép>98</N_x00B0_dép>
<Département>Dom-Tom</Département>
</Départements>
<Départements>
<N_x00B0_dép>99</N_x00B0_dép>
<Département>Etranger</Département>
</Départements>
<Départements>
<N_x00B0_dép>101</N_x00B0_dép>
<Département>Saisie en vrac</Département>
</Départements>
