=== CorentinDespierre/EDUPAIX/BasesXML/Titres.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Titres" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Titres">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="RefTitre " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="TitreTitre" index-key="Titre " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="GUID" type="9" value="faxw3z7VkUSZoDm5yO7P3A==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAB9rHDfPtWRRJmgObnI7s/cAAAAAE49vsUtQ+NAAAAAAAAAAABUAGkA
dAByAGUAcwAAAAAAAACETGKoQKZTSpAJTcVJSlLhBwAAAH2scN8+1ZFEmaA5ucju
z9xSAGUAZgBUAGkAdAByAGUAAAAAAAAARW9O1kQseUqmwKtzqbu1vAcAAAB9rHDf
PtWRRJmgObnI7s/cVABpAHQAcgBlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAA
AgAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="OrderBy" type="12" value="Titres.RefTitre"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="RefTitre" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="hExiqECmU0qQCU3FSUpS4Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Titre" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="RW9O1kQseUqmwKtzqbu1vA==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== CorentinDespierre/EDUPAIX/BasesXML/Titres.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Titres.xsd" generated="2018-03-23T09:23:33">
<Titres>
<RefTitre>1</RefTitre>
<Titre>Mlle</Titre>
</Titres>
<Titres>
<RefTitre>2</RefTitre>
<Titre>Mme</Titre>
</Titres>
<Titres>
<RefTitre>3</RefTitre>
<Titre>M.</Titre>
</Titres>
<Titres>
<RefTitre>4</RefTitre>
<Titre>Intitul√©</Titre>
</Titres>
<Titres>
<RefTitre>6</RefTitre>
<Titre>M. Mme</Titre>
</Titres>
</dataroot>
